// src/app/[locale]/contact/data/countries.ts
export const countries = [
  // الدول العربية أولاً
  { code: "sa", dialCode: "+966", name: "Saudi Arabia" },
  { code: "ae", dialCode: "+971", name: "United Arab Emirates" },
  { code: "kw", dialCode: "+965", name: "Kuwait" },
  { code: "qa", dialCode: "+974", name: "Qatar" },
  { code: "bh", dialCode: "+973", name: "Bahrain" },
  { code: "om", dialCode: "+968", name: "Oman" },
  { code: "jo", dialCode: "+962", name: "Jordan" },
  { code: "eg", dialCode: "+20", name: "Egypt" },
  { code: "lb", dialCode: "+961", name: "Lebanon" },
  { code: "sy", dialCode: "+963", name: "Syria" },
  { code: "iq", dialCode: "+964", name: "Iraq" },
  { code: "ye", dialCode: "+967", name: "Yemen" },
  { code: "ps", dialCode: "+970", name: "Palestine" },
  { code: "ma", dialCode: "+212", name: "Morocco" },
  { code: "dz", dialCode: "+213", name: "Algeria" },
  { code: "tn", dialCode: "+216", name: "Tunisia" },
  { code: "ly", dialCode: "+218", name: "Libya" },
  { code: "sd", dialCode: "+249", name: "Sudan" },
  { code: "so", dialCode: "+252", name: "Somalia" },
  { code: "dj", dialCode: "+253", name: "Djibouti" },
  { code: "km", dialCode: "+269", name: "Comoros" },
  { code: "mr", dialCode: "+222", name: "Mauritania" },

  // باقي دول العالم مرتبة أبجدياً
  { code: "af", dialCode: "+93", name: "Afghanistan" },
  { code: "al", dialCode: "+355", name: "Albania" },
  { code: "ad", dialCode: "+376", name: "Andorra" },
  { code: "ao", dialCode: "+244", name: "Angola" },
  { code: "ag", dialCode: "+1268", name: "Antigua and Barbuda" },
  { code: "ar", dialCode: "+54", name: "Argentina" },
  { code: "am", dialCode: "+374", name: "Armenia" },
  { code: "au", dialCode: "+61", name: "Australia" },
  { code: "at", dialCode: "+43", name: "Austria" },
  { code: "az", dialCode: "+994", name: "Azerbaijan" },
  { code: "bs", dialCode: "+1242", name: "Bahamas" },
  { code: "bd", dialCode: "+880", name: "Bangladesh" },
  { code: "bb", dialCode: "+1246", name: "Barbados" },
  { code: "by", dialCode: "+375", name: "Belarus" },
  { code: "be", dialCode: "+32", name: "Belgium" },
  { code: "bz", dialCode: "+501", name: "Belize" },
  { code: "bj", dialCode: "+229", name: "Benin" },
  { code: "bt", dialCode: "+975", name: "Bhutan" },
  { code: "bo", dialCode: "+591", name: "Bolivia" },
  { code: "ba", dialCode: "+387", name: "Bosnia and Herzegovina" },
  { code: "bw", dialCode: "+267", name: "Botswana" },
  { code: "br", dialCode: "+55", name: "Brazil" },
  { code: "bn", dialCode: "+673", name: "Brunei" },
  { code: "bg", dialCode: "+359", name: "Bulgaria" },
  { code: "bf", dialCode: "+226", name: "Burkina Faso" },
  { code: "bi", dialCode: "+257", name: "Burundi" },
  { code: "cv", dialCode: "+238", name: "Cape Verde" },
  { code: "kh", dialCode: "+855", name: "Cambodia" },
  { code: "cm", dialCode: "+237", name: "Cameroon" },
  { code: "ca", dialCode: "+1", name: "Canada" },
  { code: "cf", dialCode: "+236", name: "Central African Republic" },
  { code: "td", dialCode: "+235", name: "Chad" },
  { code: "cl", dialCode: "+56", name: "Chile" },
  { code: "cn", dialCode: "+86", name: "China" },
  { code: "co", dialCode: "+57", name: "Colombia" },
  { code: "cg", dialCode: "+242", name: "Congo" },
  { code: "cd", dialCode: "+243", name: "Congo (DRC)" },
  { code: "cr", dialCode: "+506", name: "Costa Rica" },
  { code: "ci", dialCode: "+225", name: "Côte d'Ivoire" },
  { code: "hr", dialCode: "+385", name: "Croatia" },
  { code: "cu", dialCode: "+53", name: "Cuba" },
  { code: "cy", dialCode: "+357", name: "Cyprus" },
  { code: "cz", dialCode: "+420", name: "Czech Republic" },
  { code: "dk", dialCode: "+45", name: "Denmark" },
  { code: "dm", dialCode: "+1767", name: "Dominica" },
  { code: "do", dialCode: "+1", name: "Dominican Republic" },
  { code: "ec", dialCode: "+593", name: "Ecuador" },
  { code: "sv", dialCode: "+503", name: "El Salvador" },
  { code: "gq", dialCode: "+240", name: "Equatorial Guinea" },
  { code: "er", dialCode: "+291", name: "Eritrea" },
  { code: "ee", dialCode: "+372", name: "Estonia" },
  { code: "sz", dialCode: "+268", name: "Eswatini" },
  { code: "et", dialCode: "+251", name: "Ethiopia" },
  { code: "fj", dialCode: "+679", name: "Fiji" },
  { code: "fi", dialCode: "+358", name: "Finland" },
  { code: "fr", dialCode: "+33", name: "France" },
  { code: "ga", dialCode: "+241", name: "Gabon" },
  { code: "gm", dialCode: "+220", name: "Gambia" },
  { code: "ge", dialCode: "+995", name: "Georgia" },
  { code: "de", dialCode: "+49", name: "Germany" },
  { code: "gh", dialCode: "+233", name: "Ghana" },
  { code: "gr", dialCode: "+30", name: "Greece" },
  { code: "gd", dialCode: "+1473", name: "Grenada" },
  { code: "gt", dialCode: "+502", name: "Guatemala" },
  { code: "gn", dialCode: "+224", name: "Guinea" },
  { code: "gw", dialCode: "+245", name: "Guinea-Bissau" },
  { code: "gy", dialCode: "+592", name: "Guyana" },
  { code: "ht", dialCode: "+509", name: "Haiti" },
  { code: "hn", dialCode: "+504", name: "Honduras" },
  { code: "hu", dialCode: "+36", name: "Hungary" },
  { code: "is", dialCode: "+354", name: "Iceland" },
  { code: "in", dialCode: "+91", name: "India" },
  { code: "id", dialCode: "+62", name: "Indonesia" },
  { code: "ir", dialCode: "+98", name: "Iran" },
  { code: "ie", dialCode: "+353", name: "Ireland" },
  { code: "il", dialCode: "+972", name: "Israel" },
  { code: "it", dialCode: "+39", name: "Italy" },
  { code: "jm", dialCode: "+1876", name: "Jamaica" },
  { code: "jp", dialCode: "+81", name: "Japan" },
  { code: "kz", dialCode: "+7", name: "Kazakhstan" },
  { code: "ke", dialCode: "+254", name: "Kenya" },
  { code: "ki", dialCode: "+686", name: "Kiribati" },
  { code: "kp", dialCode: "+850", name: "North Korea" },
  { code: "kr", dialCode: "+82", name: "South Korea" },
  { code: "xk", dialCode: "+383", name: "Kosovo" },
  { code: "kg", dialCode: "+996", name: "Kyrgyzstan" },
  { code: "la", dialCode: "+856", name: "Laos" },
  { code: "lv", dialCode: "+371", name: "Latvia" },
  { code: "ls", dialCode: "+266", name: "Lesotho" },
  { code: "lr", dialCode: "+231", name: "Liberia" },
  { code: "li", dialCode: "+423", name: "Liechtenstein" },
  { code: "lt", dialCode: "+370", name: "Lithuania" },
  { code: "lu", dialCode: "+352", name: "Luxembourg" },
  { code: "mg", dialCode: "+261", name: "Madagascar" },
  { code: "mw", dialCode: "+265", name: "Malawi" },
  { code: "my", dialCode: "+60", name: "Malaysia" },
  { code: "mv", dialCode: "+960", name: "Maldives" },
  { code: "ml", dialCode: "+223", name: "Mali" },
  { code: "mt", dialCode: "+356", name: "Malta" },
  { code: "mh", dialCode: "+692", name: "Marshall Islands" },
  { code: "mu", dialCode: "+230", name: "Mauritius" },
  { code: "mx", dialCode: "+52", name: "Mexico" },
  { code: "fm", dialCode: "+691", name: "Micronesia" },
  { code: "md", dialCode: "+373", name: "Moldova" },
  { code: "mc", dialCode: "+377", name: "Monaco" },
  { code: "mn", dialCode: "+976", name: "Mongolia" },
  { code: "me", dialCode: "+382", name: "Montenegro" },
  { code: "mz", dialCode: "+258", name: "Mozambique" },
  { code: "mm", dialCode: "+95", name: "Myanmar" },
  { code: "na", dialCode: "+264", name: "Namibia" },
  { code: "nr", dialCode: "+674", name: "Nauru" },
  { code: "np", dialCode: "+977", name: "Nepal" },
  { code: "nl", dialCode: "+31", name: "Netherlands" },
  { code: "nz", dialCode: "+64", name: "New Zealand" },
  { code: "ni", dialCode: "+505", name: "Nicaragua" },
  { code: "ne", dialCode: "+227", name: "Niger" },
  { code: "ng", dialCode: "+234", name: "Nigeria" },
  { code: "mk", dialCode: "+389", name: "North Macedonia" },
  { code: "no", dialCode: "+47", name: "Norway" },
  { code: "pk", dialCode: "+92", name: "Pakistan" },
  { code: "pw", dialCode: "+680", name: "Palau" },
  { code: "pa", dialCode: "+507", name: "Panama" },
  { code: "pg", dialCode: "+675", name: "Papua New Guinea" },
  { code: "py", dialCode: "+595", name: "Paraguay" },
  { code: "pe", dialCode: "+51", name: "Peru" },
  { code: "ph", dialCode: "+63", name: "Philippines" },
  { code: "pl", dialCode: "+48", name: "Poland" },
  { code: "pt", dialCode: "+351", name: "Portugal" },
  { code: "ro", dialCode: "+40", name: "Romania" },
  { code: "ru", dialCode: "+7", name: "Russia" },
  { code: "rw", dialCode: "+250", name: "Rwanda" },
  { code: "kn", dialCode: "+1869", name: "Saint Kitts and Nevis" },
  { code: "lc", dialCode: "+1758", name: "Saint Lucia" },
  { code: "vc", dialCode: "+1784", name: "Saint Vincent and the Grenadines" },
  { code: "ws", dialCode: "+685", name: "Samoa" },
  { code: "sm", dialCode: "+378", name: "San Marino" },
  { code: "st", dialCode: "+239", name: "São Tomé and Príncipe" },
  { code: "sn", dialCode: "+221", name: "Senegal" },
  { code: "rs", dialCode: "+381", name: "Serbia" },
  { code: "sc", dialCode: "+248", name: "Seychelles" },
  { code: "sl", dialCode: "+232", name: "Sierra Leone" },
  { code: "sg", dialCode: "+65", name: "Singapore" },
  { code: "sk", dialCode: "+421", name: "Slovakia" },
  { code: "si", dialCode: "+386", name: "Slovenia" },
  { code: "sb", dialCode: "+677", name: "Solomon Islands" },
  { code: "za", dialCode: "+27", name: "South Africa" },
  { code: "ss", dialCode: "+211", name: "South Sudan" },
  { code: "es", dialCode: "+34", name: "Spain" },
  { code: "lk", dialCode: "+94", name: "Sri Lanka" },
  { code: "sr", dialCode: "+597", name: "Suriname" },
  { code: "se", dialCode: "+46", name: "Sweden" },
  { code: "ch", dialCode: "+41", name: "Switzerland" },
  { code: "tj", dialCode: "+992", name: "Tajikistan" },
  { code: "tz", dialCode: "+255", name: "Tanzania" },
  { code: "th", dialCode: "+66", name: "Thailand" },
  { code: "tl", dialCode: "+670", name: "Timor-Leste" },
  { code: "tg", dialCode: "+228", name: "Togo" },
  { code: "to", dialCode: "+676", name: "Tonga" },
  { code: "tt", dialCode: "+1868", name: "Trinidad and Tobago" },
  { code: "tr", dialCode: "+90", name: "Turkey" },
  { code: "tm", dialCode: "+993", name: "Turkmenistan" },
  { code: "tv", dialCode: "+688", name: "Tuvalu" },
  { code: "ug", dialCode: "+256", name: "Uganda" },
  { code: "ua", dialCode: "+380", name: "Ukraine" },
  { code: "gb", dialCode: "+44", name: "United Kingdom" },
  { code: "us", dialCode: "+1", name: "United States" },
  { code: "uy", dialCode: "+598", name: "Uruguay" },
  { code: "uz", dialCode: "+998", name: "Uzbekistan" },
  { code: "vu", dialCode: "+678", name: "Vanuatu" },
  { code: "va", dialCode: "+39", name: "Vatican City" },
  { code: "ve", dialCode: "+58", name: "Venezuela" },
  { code: "vn", dialCode: "+84", name: "Vietnam" },
  { code: "zm", dialCode: "+260", name: "Zambia" },
  { code: "zw", dialCode: "+263", name: "Zimbabwe" },
];
